cas:
  adminPagesSecurity:
    ip: 127.0.0.1
  authn:
    accept:
      users: admin::admin
  #  theme:
  #    defaultThemeName: "springboot" #默认主题
  serviceRegistry:
    initFromJson: true #开启json服务注册
    watcherEnabled: true #自动扫描服务配置，默认开启
    schedule:
      repeatInterval: 120000 #120秒扫描一遍
      startDelay: 15000 #延迟15秒开启
    json:
      location: classpath:/services #默认json/yml资源加载路径为resources/services
  logout:
    followServiceRedirects: true #登出后允许跳转到指定页面
  ticket:
    st:
      timeToKillInSeconds: 20 #ST票据生命周期
    pt:
      timeToKillInSeconds: 20 #PT票据生命周期
    registry:
      redis:
        host: 172.16.253.182
        database: 1
        port: 6379
        password: 123321
        timeout: 2000
        useSsl: false
        usePool: false
  tgc:
    crypto:
      enabled: false #表示不对TGC进行加密，默认是true，TGC其实就是TGT经过JWT加密后的值而已
slo:
  callbacks:
    disabled: false #是否禁用单点登出
endpoints:
  enabled: false
  restart:
    enabled: false
  sensitive: true
  shutdown:
    enabled: false
management:
  add-application-context-header: false
  context-path: /status
  health:
    status:
      order: WARN, DOWN, OUT_OF_SERVICE, UNKNOWN, UP
  security:
    enabled: true
    roles: ACTUATOR,ADMIN
    sessions: if_required
security:
  basic:
    authorize-mode: role
    path: /cas/status/**
server:
  compression:
    enabled: true
    mime-types: application/javascript,application/json,application/xml,text/html,text/xml,text/plain
  connection-timeout: 20000
  context-parameters:
    isLog4jAutoInitializationDisabled: true
  context-path: /cas
  error:
    include-stacktrace: ALWAYS
  max-http-header-size: 2097152
  port: 8443
  session:
    cookie:
      http-only: true
    timeout: 300
    tracking-modes: COOKIE
  ssl:
    key-password: changeit
    key-store: file:/etc/cas/thekeystore
    key-store-password: changeit
  tomcat:
    accesslog:
      enabled: true
      pattern: '%t %a "%r" %s (%D ms)'
      suffix: .log
    basedir: build/tomcat
    max-http-post-size: 2097152
    max-threads: 200
    min-spare-threads: 10
    port-header: X-Forwarded-Port
    protocol-header: X-Forwarded-Proto
    protocol-header-https-value: https
    remote-ip-header: X-FORWARDED-FOR
    uri-encoding: UTF-8
  use-forward-headers: true
spring:
  aop:
    auto: true
    proxy-target-class: true
  cloud:
    bus:
      enabled: false
    config:
      allow-override: true
      override-none: false
      override-system-properties: false
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  thymeleaf:
    cache: true
    encoding: UTF-8
    mode: HTML
    template-resolver-order: 100
