cas:
  adminPagesSecurit:
  ip: 127.0.0.1
  authn:
    accept:
      users: admin::admin
  serviceRegistry:
    initFromJson: true #开启json服务注册
  logout:
    followServiceRedirects: true #登出后允许跳转到指定页面
tgt:
  maxTimeToLiveInSeconds: 28800 #指定Session的最大有效时间,即从生成到指定时间后就将超时,默认28800s,即8小时
  timeToKillInSeconds: 7200 #指定用户操作的超时时间,即用户在多久不操作后就超时,默认7200s,即2小时。
  #还要注意客户端web.xml配置的超时时间，即只有客户端配置超时时间不大于tgt.timeToKillInSeconds时才能看见服务端设置的效果
st:
  timeToKillInSeconds: 10 #指定service ticket的有效时间,默认10s， 这也是debug追踪CAS应用认证过程中经常会失败的原因,因为追踪的时候service ticket已经过了10秒有效期了
slo:
  callbacks:
    disabled: false #是否禁用单点登出
endpoints:
  enabled: false
  restart:
    enabled: false
  sensitive: true
  shutdown:
    enabled: false
management:
  add-application-context-header: false
  context-path: /status
  health:
    status:
      order: WARN, DOWN, OUT_OF_SERVICE, UNKNOWN, UP
  security:
    enabled: true
    roles: ACTUATOR,ADMIN
    sessions: if_required
security:
  basic:
    authorize-mode: role
    path: /cas/status/**
server:
  compression:
    enabled: true
    mime-types: application/javascript,application/json,application/xml,text/html,text/xml,text/plain
  connection-timeout: 20000
  context-parameters:
    isLog4jAutoInitializationDisabled: true
  context-path: /cas
  error:
    include-stacktrace: ALWAYS
  max-http-header-size: 2097152
  port: 8443
  session:
    cookie:
      http-only: true
    timeout: 300
    tracking-modes: COOKIE
  ssl:
    key-password: changeit
    key-store: file:/etc/cas/thekeystore
    key-store-password: changeit
  tomcat:
    accesslog:
      enabled: true
      pattern: '%t %a "%r" %s (%D ms)'
      suffix: .log
    basedir: build/tomcat
    max-http-post-size: 2097152
    max-threads: 200
    min-spare-threads: 10
    port-header: X-Forwarded-Port
    protocol-header: X-Forwarded-Proto
    protocol-header-https-value: https
    remote-ip-header: X-FORWARDED-FOR
    uri-encoding: UTF-8
  use-forward-headers: true
spring:
  aop:
    auto: true
    proxy-target-class: true
  cloud:
    bus:
      enabled: false
    config:
      allow-override: true
      override-none: false
      override-system-properties: false
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  thymeleaf:
    cache: true
    encoding: UTF-8
    mode: HTML
    template-resolver-order: 100
